# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webapptktest34526

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://tktestregistry111.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8682975093754c1dbaeaa781d9688926 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4853546210a542458426051cde623b51 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: tktestregistry111.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8682975093754c1dbaeaa781d9688926 }}/webimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapptktest34526'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_617c44c3050b46f99e8e9265edc42024 }}
        images: 'tktestregistry111.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8682975093754c1dbaeaa781d9688926 }}/webimage:${{ github.sha }}'